/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import { Material, Mesh } from 'three'

export function Skybox(props:any) {
  const { nodes, materials } = useGLTF('/skybox.glb')as unknown as {
    nodes: { Sphere: Mesh }
    materials: { [key: string]: Material }
  }

  useEffect(() => {
    if (materials['Material.001']) {
        materials['Material.001'].transparent=true;
        materials['Material.001'].opacity=0.2;
    }
}, [materials])

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.001']}
      />
    </group>
  )
}

useGLTF.preload('/skybox.glb')